#!/usr/bin/env python3
"""Deterministic procedural water meshes/textures. Stdlib only; no runtime build dependency."""
import hashlib,json,math,random,struct,sys,zlib
from pathlib import Path
root=Path(__file__).resolve().parents[2]/'src/assets/models/milkyway'
check='--check' in sys.argv
report={}
def save(name,data):
 p=root/name
 if check: assert p.read_bytes()==data,name
 else:p.write_bytes(data)
 report[name]={'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
def mesh(name,dome):
 sectors=96;rings=20;radius=2.31
 points=[(0.,0.,-1. if dome else 0.)];uv=[(.5,.5)];faces=[]
 for ring in range(1,rings+1):
  r=ring/rings
  for j in range(sectors):
   a=2*math.pi*j/sectors
   z=-(1-r*r)**2 if dome else .006*math.sin(r*37+a*3)*r*(1-r)
   points.append((radius*r*math.cos(a),radius*r*math.sin(a),z));uv.append((.5+.5*r*math.cos(a),.5+.5*r*math.sin(a)))
 for j in range(sectors):faces.append((0,1+(j+1)%sectors,1+j))
 for ring in range(1,rings):
  inner=1+(ring-1)*sectors;outer=inner+sectors
  for j in range(sectors):
   k=(j+1)%sectors
   faces.extend([(inner+j,inner+k,outer+k),(inner+j,outer+k,outer+j)])
 for f in faces:
  a,b,c=[points[i] for i in f];u=[b[i]-a[i] for i in range(3)];v=[c[i]-a[i] for i in range(3)]
  assert sum(x*x for x in (u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]))>1e-16
 assert len(points)<65535 and len(faces)==3744
 lines=['# Procedural OZ Stargate water geometry; generated by build-wormhole.py','o '+name]
 lines+=['v %.7f %.7f %.7f'%p for p in points]
 lines+=['vt %.7f %.7f'%p for p in uv]
 lines+=['f '+' '.join(f'{i+1}/{i+1}' for i in f) for f in faces]
 save('articulated-'+name+'.obj',('\n'.join(lines)+'\n').encode())
 report['articulated-'+name+'.obj'].update(vertices=len(points),triangles=len(faces),radius=radius)
def png(name,overlay):
 size=512;randomizer=random.Random(51421)
 waves=[(randomizer.uniform(0,math.tau),f,randomizer.uniform(0,math.tau)) for f in [5,7,11,17,23,31,43]]
 raw=bytearray()
 for y in range(size):
  raw.append(0)
  for x in range(size):
   u=(x+.5)/size*2-1;v=(y+.5)/size*2-1;r=math.hypot(u,v)
   warp=sum(math.sin((u*math.cos(a)+v*math.sin(a))*f+p)/(1+i*.5) for i,(a,f,p) in enumerate(waves))
   vein=(.5+.5*math.cos(warp*3.8+r*28))**12
   glow=(.5+.5*math.sin(warp*1.8+r*11))
   if overlay:color=(175,221,244,int((14+105*vein)*max(0,min(1,(1-r)*12))))
   else:
    light=.16+.39*glow+.43*vein
    color=(int(24+166*light),int(62+165*light),int(94+148*light),255)
   raw.extend(color)
 def chunk(kind,data):return struct.pack('!I',len(data))+kind+data+struct.pack('!I',zlib.crc32(kind+data)&0xffffffff)
 data=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('!2I5B',size,size,8,6,0,0,0))+chunk(b'IDAT',zlib.compress(raw,9))+chunk(b'IEND',b'')
 save(name,data)
mesh('wormhole-surface',False);mesh('wormhole-surge',True)
png('wormhole-water.png',False);png('wormhole-ripples.png',True)
out=json.dumps(report,indent=2)+'\n'
if check:assert (root/'wormhole-report.json').read_text()==out
else:(root/'wormhole-report.json').write_text(out)
print('Wormhole assets verified:',len(report),'assets; 3744 triangles per surface')
