#!/usr/bin/env python3
"""Rebuild or verify the checked-in derived DHD meshes from the user archive.

Only an offline Blender 3.3 binary is required. Maven uses generated OBJ files directly.
"""
import argparse
import hashlib
import json
import subprocess
import tempfile
from pathlib import Path
from zipfile import ZipFile

ARCHIVE_SHA = '8d9f9a91305d9dd5a4245f12644c9c01c673cb6596ecc148b041fd4a303590aa'
BLEND_SHA = 'a90ada3743ecb7cbbde078359dbb00f2e67be585f3c449583ddb432b7992ce9e'
ROOT = Path(__file__).resolve().parents[2] / 'src/assets/models/dhd'
BUILDER = Path(__file__).with_name('build-supplied-dhd.py')
NOTICE = '''Source: Stargate DHD by blenderjunky, BlendSwap asset 75540 (current page /blend/13419).
Original archive: Stargate DHD.zip; DHD.blend SHA256: a90ada3743ecb7cbbde078359dbb00f2e67be585f3c449583ddb432b7992ce9e.
Source listing: https://www.blendswap.com/blend/13419
License: creator marks the model CC0; the archived license document also marks its
Stargate design as Fan Art and warns against commercial use. This project and its
user-provided test deployment are noncommercial. CC0 does not settle third-party
rights in the underlying Stargate design. The verbatim archived license notice
is included as supplied-dhd-LICENSE.html.
Changes: applied the authored base Mirror modifier, omitted Subsurf modifiers,
decimated high-poly groups, triangulated, transformed Blender Z-up to Rising World
Y-up, scaled to approximately 1.45m diameter and 1.12m height, separated material
groups, seven individually illuminated buttons and matching glyphs, and added
box-projected UVs to the stone body.
No original blend or preview image is included in the plugin.
Generated by scripts/assets/rebuild-supplied-dhd.py with Blender 3.3.15.
'''
parser = argparse.ArgumentParser()
parser.add_argument('archive', type=Path)
parser.add_argument('blender', type=Path)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
assert hashlib.sha256(args.archive.read_bytes()).hexdigest() == ARCHIVE_SHA
with ZipFile(args.archive) as source, tempfile.TemporaryDirectory(prefix='stargate-dhd-build.') as temp:
    work = Path(temp)
    blend = source.read('DHD.blend')
    assert hashlib.sha256(blend).hexdigest() == BLEND_SHA
    blend_path = work / 'DHD.blend'; blend_path.write_bytes(blend)
    result = subprocess.run([str(args.blender), '--background', str(blend_path),
                             '--python', str(BUILDER), '--', str(work)],
                            text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if result.returncode:
        raise RuntimeError(result.stdout[-5000:])
    (work/'supplied-dhd-LICENSE.html').write_bytes(source.read('75540 - Stargate DHD - License.html'))
    (work/'supplied-dhd-SOURCE-NOTICE.txt').write_text(NOTICE)
    generated = sorted(work.glob('supplied-dhd-*'))
    assert len(generated) == 24, [p.name for p in generated]
    for path in generated:
        destination = ROOT / path.name
        if args.check:
            assert destination.read_bytes() == path.read_bytes(), path.name
        else:
            destination.write_bytes(path.read_bytes())
    report=json.loads((work/'supplied-dhd-build-report.json').read_text())
    print('verified' if args.check else 'generated', len(generated),'files;',
          report['totalTriangles'],'triangles; Blender',report['blender'])
